name: t2d_single_cell_multiomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - pyarrow
  - pyyaml
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - shap
  - xgboost
  - r-base
  - r-yaml
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-stringr
  - r-tibble
  - r-purrr
  - r-data.table
  - r-patchwork
  - r-arrow
  - bioconductor-deseq2
  - bioconductor-genomicranges
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - pip:
      - BorutaShap
      - scRiskCell
